### ISSUE TITLE
Adding and editing Fishki

### ISSUE THREAD

**Issue by rokcetfuel** [rokcetfuel/fishki#11]

**Comment by asia12345678901** [comment]
view height too short because menu overlays content

**Comment by asia12345678901** [comment]
when keyboard hides after clicking a tag, the "New fishka" panel appears and disrupts the view

**Comment by asia12345678901** [comment]
When a name of a setup is confirmed, the keyboard doesn't hide.

**Comment by ForteAnother** [comment]
When creating new setup, it is only possible to pick "English" or "Polish" in "Translations"

**Comment by ForteAnother** [comment]
When creating new setup, it's not clear which language should be in "Phrases" and which in "Translations"

**Comment by ForteAnother** [comment]
It is possible to create empty Fishka, if user clicks on the second "Ok" button

**Comment by rokcetfuel** [comment]
> view height too short because menu overlays content

I will add some cute stuff on the bottom of the home view under fishki

**Comment by rokcetfuel** [comment]
> When a name of a setup is confirmed, the keyboard doesn't hide.

Will be fixed at validation

**Comment by rokcetfuel** [comment]
> When creating new setup, it is only possible to pick "English" or "Polish" in "Translations"

That's the desired effect, Sip Martinis

**Comment by ForteAnother** [comment]
> > When creating new setup, it is only possible to pick "English" or "Polish" in "Translations"
> 
> That's the desired effect, Sip Martinis

Well that's not very diverse of us, is it?

**Comment by rokcetfuel** [comment]
> It's not clear which language should be in "Phrases" and which in "Translations"

What do you suggest we do?

> It is only possible to pick "English" or "Polish" in "Translations"

I can add more, but you will have to test it more

**Comment by asia12345678901** [comment]
> > view height too short because menu overlays content
> 
> I will add some cute stuff on the bottom of the home view under fishki

Oh that's great :D

**Comment by asia12345678901** [comment]
> > When a name of a setup is confirmed, the keyboard doesn't hide.
> 
> Will be fixed at validation

Great!

**Comment by ForteAnother** [comment]
> > It's not clear which language should be in "Phrases" and which in "Translations"
> 
> What do you suggest we do?
> 
> > It is only possible to pick "English" or "Polish" in "Translations"
> 
> I can add more, but you will have to test it more

I'll test it one more time then

**Comment by ForteAnother** [comment]
> What do you suggest we do?

How about something like "Translations (learned language)" and "Phrases (known language)"?
