### ISSUE TITLE
Validation during any deletion

### ISSUE THREAD

**Issue by asia12345678901** [rokcetfuel/fishki#16]
- [ ]  deleting Setup (Settings)
- [ ] deleting Fishka (Edit)

**Comment by ForteAnother** [comment]
User should be asked to confirm before deleting a whole setup, preferably with notice that all data will be lost

**Comment by rokcetfuel** [comment]
> User should be asked to confirm before deleting a whole setup, preferably with notice that all data will be lost

Will do - all the eyes on me in the center of the fishka just like a circus

**Comment by ForteAnother** [comment]
Oops I did it again to your heart, got lost in the issue. I'll help with the change :)
