### ISSUE TITLE
Validation of empty fields

### ISSUE THREAD

**Issue by asia12345678901** [rokcetfuel/fishki#17]
Settings
- [x] current setup: name
- [x] new setup: empty name, empty select, same select

Add 
- [x] empty phrase or translation (pronunciation can be empty)
- [x] don't allow creating an empty tag here
- [x] tag already exists

Edit
- [x] empty phrase or translation (pronunciation can be empty)
- [x] don't allow creating an empty tag here
- [x] tag already exists

Tag manager
- [x] don't allow creating an empty tag here
- [x] tag already exists

**Comment by ForteAnother** [comment]
It is possible to add empty tag, it shouldn't be

**Comment by rokcetfuel** [comment]
> It is possible to add empty tag, it shouldn't be

I must confess I still believe (still believe) it will be done eventually

**Comment by ForteAnother** [comment]
You better work!
