### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by asia12345678901** [rokcetfuel/fishki#19]

**Comment by ForteAnother** [comment]
It's not possible to fully remove a tag when editing fishka

**Comment by ForteAnother** [comment]
It is possible to create an empty tag, it shouldn't be

**Comment by ForteAnother** [comment]
It's not possible to edit a tag (for example, if a mistake was made)

**Comment by rokcetfuel** [comment]
> It's not possible to edit a tag (for example, if a mistake was made)
> It's not possible to fully remove a tag when editing fishka

Yes it is buddie, in Settings in Tag manager

**Comment by ForteAnother** [comment]
Confirmed it works, thank you
