### ISSUE TITLE
Desktop layout adjustments

### ISSUE THREAD

**Issue by rokcetfuel** [rokcetfuel/fishki#22]
- [ ] Desktop layout needs to be adjusted, Fishki are way too wide to be convenient

**Comment by ForteAnother** [comment]
When viewing all created Fishki, in the view that allows for sorting and choosing tags (right-most button), there is no "<" button above to go back, users have to click on "Ok"

**Comment by ForteAnother** [comment]
Desktop layout needs to be adjusted, Fishki are way too wide to be convenient

**Comment by rokcetfuel** [comment]
> When viewing all created Fishki, in the view that allows for sorting and choosing tags (right-most button), there is no "<" button above to go back, users have to click on "Ok"

is that necessary tho

**Comment by ForteAnother** [comment]
> >  is that necessary tho

I mean, if we don't care about user experience, sure, let's just leave it as is :-)

**Comment by rokcetfuel** [comment]
> > > is that necessary tho
> 
> I mean, if we don't care about user experience, sure, let's just leave it as is :-)

Fine, will do, don't stop, make it pop DJ
